spring:
  info:
    version: 1.0
  application:
    name: liquibase-test
  ##数据库配置
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://192.168.137.100:3306/liquibase?useUnicode=true&characterEncoding=UTF-8
#    username: root
#    password: 123456
#    hikari:
#      maximum-pool-size: 3
  ## liquibase
#  liquibase:
    # spring boot 2以上禁用Spring Boot自动运行Liquibase
    #Spring Boot在应用程序启动时自动运行Liquibase数据库迁移。
#    enabled: false
    # 禁止清库执行
#    drop-first: true
#    change-log: classpath:/db.changelog-master.xml
#    database-change-log-table: lg_db_change_log
#    database-change-log-lock-table: lg_db_change_log_lock





liquibase:
  #版本信息配置
  versions:
    ## 1.0 版本
  - version: v1.0
    change-logs:
    - {database: agreement-db,change-log: RELEASE_1.0_changelog.xml}
    - {database: user-db,change-log: RELEASE_1.0_changelog.xml}
#
    ## 1.1 版本
  - version: v1.1
    change-logs:
    - database: agreement-db
      change-Log: RELEASE_1.1_changelog.xml
    - database: user-db
      change-Log: RELEASE_1.1_changelog.xml

    ## 1.2 版本
  - version: v1.2
    change-logs:
    - database: agreement-db
      change-Log: RELEASE_1.2_changelog.xml
    - database: user-db
      change-Log: RELEASE_1.1_changelog.xml

  #版本数据库信息配置
  databases:
    agreement-db:
      driver: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.137.100:3306/agreement_db?useUnicode=true&characterEncoding=UTF-8
      username: root
      password: 123456
#      database-change-log-table: agreement_db_change_log
#      database-change-log-lock-table: agreement_db_change_log_lock
    user-db:
      driver: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.137.100:3306/user_db?useUnicode=true&characterEncoding=UTF-8
      username: root
      password: 123456
#      database-change-log-table: user_db_change_log
#      database-change-log-lock-table: user_db_change_log_lock
